openapi: 3.0.3
info:
  title: 'users-system-api'
  description: 'A REST API for a users system'
  version: 1.1.0

servers:
  - url: https://frayfray-users-system-api.herokuapp.com/
    description: Production server

components:
  schemas:
    User:
      properties:
        username:
          type: string
          minimum: 3
          maximum: 20
        email:
          type: string
          pattern: "[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?"
        password:
          type: string
          minimum: 6
      required:
        - username
        - email
        - password
paths:
  /users:
    post:
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Returns the created user 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Bad or malformed request
        '409':
          description: Email already exists
        '500':
          description: Internal server error
